version: '3'

services:
  reverse:
    container_name: reverse
    hostname: reverse
    restart: always
    network_mode: host
    image: nginx
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./config/:/etc/nginx
      - ./certs/:/etc/ssl/private

